/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Wed Aug 30 11:22:49 2017. */

#include "fk-app.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t fk_app_QueryCapabilities_fields[2] = {
    PB_FIELD(  1, INT64   , SINGULAR, STATIC  , FIRST, fk_app_QueryCapabilities, version, version, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_app_SensorCapabilities_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_app_SensorCapabilities, index, index, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, fk_app_SensorCapabilities, name, index, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_app_Capabilities_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_app_Capabilities, version, version, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, fk_app_Capabilities, name, version, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, fk_app_Capabilities, sensors, name, &fk_app_SensorCapabilities_fields),
    PB_LAST_FIELD
};

const pb_field_t fk_app_WireMessageQuery_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_app_WireMessageQuery, type, type, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fk_app_WireMessageQuery, queryCapabilities, type, &fk_app_QueryCapabilities_fields),
    PB_LAST_FIELD
};

const pb_field_t fk_app_WireMessageReply_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_app_WireMessageReply, type, type, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fk_app_WireMessageReply, capabilities, type, &fk_app_Capabilities_fields),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fk_app_WireMessageQuery, queryCapabilities) < 65536 && pb_membersize(fk_app_WireMessageReply, capabilities) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_fk_app_QueryCapabilities_fk_app_SensorCapabilities_fk_app_Capabilities_fk_app_WireMessageQuery_fk_app_WireMessageReply)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fk_app_WireMessageQuery, queryCapabilities) < 256 && pb_membersize(fk_app_WireMessageReply, capabilities) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_fk_app_QueryCapabilities_fk_app_SensorCapabilities_fk_app_Capabilities_fk_app_WireMessageQuery_fk_app_WireMessageReply)
#endif


/* @@protoc_insertion_point(eof) */
